# Generated by Django 4.2.13 on 2024-06-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_hash',
        ),
    ]
